[package]
name = "noise-functions-demo"
version = "0.0.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", default-features = false, features = ["default_fonts", "glow"] }
log = "0.4"
noise-functions-config = { version = "0.1.0", features = ["nightly-simd"] }
web-time = "1.1.0"
ahash = { version = "0.8.11", default-features = false } # just fixing something

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

[profile.release]
opt-level = 2

[profile.dev.package."*"]
opt-level = 2

[workspace]
members = [
  "generate-icons",
]
